name: core-framework

services:
  app:
    container_name: core-framework-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - HOST=0.0.0.0
    mem_limit: 512m
    mem_reservation: 256m
    restart: unless-stopped
