FROM node:22-alpine

# Cài đặt bash và curl phục vụ kiểm tra kết nối & quản trị
RUN apk add --no-cache bash curl

WORKDIR /app/frontend

# Copy cấu hình package frontend
COPY frontend/package*.json ./

# Cài đặt dependencies cho Frontend
RUN npm install

# Copy mã nguồn frontend ban đầu
COPY frontend ./
COPY docker/frontend/entrypoint.dev.sh /app/docker/frontend/entrypoint.dev.sh

RUN chmod +x /app/docker/frontend/entrypoint.dev.sh

EXPOSE 5175

ENTRYPOINT ["/app/docker/frontend/entrypoint.dev.sh"]
